build:
  modules:
  - ninja
  dependencies:
  - ecmwf/ecbuild
  - MathisRosenhauer/libaec@master
  - ecmwf/eccodes
  - ecmwf/eckit
  - ecmwf/odc
  python_dependencies:
  - ecmwf/eccodes-python@develop
  - ecmwf/cfgrib@master
  - ecmwf/pdbufr@master
  - ecmwf/pyodc@develop
  env:
  - ECCODES_SAMPLES_PATH=$ECCODES_DIR/share/eccodes/samples
  - ECCODES_DEFINITION_PATH=$ECCODES_DIR/share/eccodes/definitions
  parallel: 64
