name: Notify CI

on:
  workflow_dispatch:
    inputs:
      job:
        required: true
      job_context:
        required: true
      needs_context:
        required: true
      branch:
        required: true
      sha:
        required: true
      workflow:
        required: true
      run_id:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Teams notification
      uses: ecmwf-actions/notify-teams@v1
      with:
        incoming_webhook: ${{ secrets.MS_TEAMS_INCOMING_WEBHOOK }}
        job: job
        job_context: job_context
        needs_context: needs_context
        branch: branch
        sha: sha
        workflow: workflow
        run_id: run_id
